/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/alu_control.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/alu.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/control_unit.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/data_memory.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/ex_mem_reg.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/forwarding_unit.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/id_ex_reg.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/if_id_reg.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/imm_gen.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/instr_fields.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/instr_mem.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/mem_wb_reg.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/mul_div_unit.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/pc.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/regfile.v
/media/tommyhuynh/LearningDocuments/RISCV_v2/sim/../rtl/top.v
